# Generated by Django 4.0.3 on 2022-04-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
